# Misc performance core tuning
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

binds {
    scroll_event_delay = 0
    hide_special_on_workspace_change = true
}

dwindle {
    preserve_split = true
    smart_split = false
    smart_resizing = false
    precise_mouse_move = true
}